# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-26 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sc_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_name', models.CharField(max_length=32)),
                ('sc_address', models.CharField(max_length=32)),
                ('sc_manager', models.CharField(max_length=32)),
                ('sc_phone', models.CharField(max_length=32)),
                ('dk_num', models.IntegerField(default=0)),
                ('ctime', models.DateField(auto_now_add=True, null=True)),
                ('uptime', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='store_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=32)),
                ('store_order', models.CharField(max_length=32)),
                ('scName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.sc_list')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
