# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-07-26 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_list',
            old_name='scName',
            new_name='sc',
        ),
    ]
